{
  "openapi": "3.0.3",
  "info": {
    "description": "First pass at back-end API schema for the [MQTT Device Manager](https://github.com/Calvinxc1/MQTT_device_manager) app\n",
    "version": "0.0.0",
    "title": "MQTT Device Manager API",
    "contact": {
      "email": "jcherry@gmail.com"
    },
    "license": {
      "name": "GNU General Public License v3.0",
      "url": "https://github.com/Calvinxc1/MQTT_device_manager/blob/main/LICENSE"
    }
  },
  "paths": {
    "/device": {
      "get": {
        "summary": "Returns a listing of devices",
        "description": "Takes as input filter criteria for devices based on name, status, and location. Returns a listing of such devices. No specified filters would return a complete device listing.\n",
        "parameters": [
          {
            "$ref": "#/components/parameters/deviceName"
          },
          {
            "$ref": "#/components/parameters/deviceStatus"
          }
        ],
        "tags": [
          "Device"
        ],
        "responses": {
          "200": {
            "description": "Successful return of devices",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeviceGetResp200"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400-UserError"
          },
          "500": {
            "$ref": "#/components/responses/500-ServerError"
          }
        }
      },
      "post": {
        "summary": "Creates a new device",
        "description": "Takes as input a device name and location, and creates a new device for it.\n",
        "tags": [
          "Device"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DevicePostReq"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful creation of device record",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DevicePostResp200"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400-UserError"
          },
          "500": {
            "$ref": "#/components/responses/500-ServerError"
          }
        }
      }
    },
    "/device/{deviceId}": {
      "get": {
        "summary": "Returns specific device information",
        "description": "Returns a specific device's detailed information by `deviceId`.\n",
        "tags": [
          "Device"
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/deviceId"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful return of device info",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeviceGetSpecificResp200"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400-UserError"
          },
          "500": {
            "$ref": "#/components/responses/500-ServerError"
          }
        }
      },
      "put": {
        "summary": "Edits a specific device",
        "description": "Edits information on a specific device: name, location, measurement endpoints.\n",
        "tags": [
          "Device"
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/deviceId"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DevicePutSpecificReq"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful editing of device info, response includes a copy of what an updated `GET` request on that device would contain since updating.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DevicePutSpecificResp200"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400-UserError"
          },
          "500": {
            "$ref": "#/components/responses/500-ServerError"
          }
        }
      },
      "delete": {
        "summary": "Deletes a device",
        "description": "Deletes a specific device's information, including measurement endpoints.\n",
        "tags": [
          "Device"
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/deviceId"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful deletion of device",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeviceDeleteSpecificResp200"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400-UserError"
          },
          "500": {
            "$ref": "#/components/responses/500-ServerError"
          }
        }
      }
    },
    "/sensor": {
      "get": {
        "summary": "Returns a listing of sensors",
        "description": "Take input filter criteria for sensors based on name, status, location, attached device. Returns a listing of such sensors. No specified filters would return a complete listing of all sensors.\n",
        "tags": [
          "Sensor"
        ],
        "responses": {
          "200": {
            "description": "Successful return of sensors"
          },
          "400": {
            "$ref": "#/components/responses/400-UserError"
          },
          "500": {
            "$ref": "#/components/responses/500-ServerError"
          }
        }
      },
      "post": {
        "summary": "Creates a new sensor",
        "description": "Takes as input a sensor name, location, and attached device, and creates a new sensor for it.\n",
        "tags": [
          "Sensor"
        ],
        "responses": {
          "200": {
            "description": "Successful creation of sensor record"
          },
          "400": {
            "$ref": "#/components/responses/400-UserError"
          },
          "500": {
            "$ref": "#/components/responses/500-ServerError"
          }
        }
      }
    },
    "/sensor/{sensorId}": {
      "get": {
        "summary": "Returns specific sensor information",
        "description": "Returns a specific sensor's detailed information.\n",
        "tags": [
          "Sensor"
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/sensorId"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful return of sensor info"
          },
          "400": {
            "$ref": "#/components/responses/400-UserError"
          },
          "500": {
            "$ref": "#/components/responses/500-ServerError"
          }
        }
      },
      "put": {
        "summary": "Edits a specific sensor",
        "description": "Edits information on a specific sensor: name, location, measurement type.\n",
        "tags": [
          "Sensor"
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/sensorId"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful editing of sensor info"
          },
          "400": {
            "$ref": "#/components/responses/400-UserError"
          },
          "500": {
            "$ref": "#/components/responses/500-ServerError"
          }
        }
      },
      "delete": {
        "summary": "Deletes a sensor",
        "description": "Deletes a specific sensor record.\n",
        "tags": [
          "Sensor"
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/sensorId"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful deletion of sensor"
          },
          "400": {
            "$ref": "#/components/responses/400-UserError"
          },
          "500": {
            "$ref": "#/components/responses/500-ServerError"
          }
        }
      }
    },
    "/alert": {
      "get": {
        "summary": "Returns a listing of alerts",
        "description": "Takes as input filter criteria for alerts based on name, device, and sensor. Returns a listing of such alerts. No specified filters would return a complete alerts listing.\n",
        "tags": [
          "Alert"
        ],
        "responses": {
          "200": {
            "description": "Successful return of alerts"
          },
          "400": {
            "$ref": "#/components/responses/400-UserError"
          },
          "500": {
            "$ref": "#/components/responses/500-ServerError"
          }
        }
      },
      "post": {
        "summary": "Creates a new alert",
        "description": "Takes as input an alert name, attached sensor, and creates a new alert for it.\n",
        "tags": [
          "Alert"
        ],
        "responses": {
          "200": {
            "description": "Successful creation of alert record"
          },
          "400": {
            "$ref": "#/components/responses/400-UserError"
          },
          "500": {
            "$ref": "#/components/responses/500-ServerError"
          }
        }
      }
    },
    "/alert/{alertId}": {
      "get": {
        "summary": "Returns specific alert information",
        "description": "Returns a specific alert's detailed information.\n",
        "tags": [
          "Alert"
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/alertId"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful return of alert info"
          },
          "400": {
            "$ref": "#/components/responses/400-UserError"
          },
          "500": {
            "$ref": "#/components/responses/500-ServerError"
          }
        }
      },
      "put": {
        "summary": "Edits a specific alert",
        "description": "Edits information on a specific alert: name, sensor.\n",
        "tags": [
          "Alert"
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/alertId"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful editing of alert info"
          },
          "400": {
            "$ref": "#/components/responses/400-UserError"
          },
          "500": {
            "$ref": "#/components/responses/500-ServerError"
          }
        }
      },
      "delete": {
        "summary": "Deletes an alert",
        "description": "Deletes a specific alert's information.\n",
        "tags": [
          "Alert"
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/alertId"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful deletion of alert"
          },
          "400": {
            "$ref": "#/components/responses/400-UserError"
          },
          "500": {
            "$ref": "#/components/responses/500-ServerError"
          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "deviceId": {
        "name": "deviceId",
        "in": "path",
        "description": "Device ID of a device",
        "required": true,
        "schema": {
          "$ref": "#/components/schemas/deviceId"
        }
      },
      "sensorId": {
        "name": "sensorId",
        "in": "path",
        "description": "Sensor ID of a sensor",
        "required": true,
        "schema": {
          "$ref": "#/components/schemas/sensorId"
        }
      },
      "alertId": {
        "name": "alertId",
        "in": "path",
        "description": "Alert ID of an alert",
        "required": true,
        "schema": {
          "$ref": "#/components/schemas/alertId"
        }
      },
      "deviceName": {
        "name": "deviceName",
        "in": "query",
        "description": "Name filter of devices, uses \\*like\\* matching",
        "required": false,
        "schema": {
          "type": "string"
        }
      },
      "deviceStatus": {
        "name": "deviceStatus",
        "in": "query",
        "description": "Device status filter",
        "required": false,
        "schema": {
          "$ref": "#/components/schemas/deviceStatus"
        }
      },
      "deviceSensorId": {
        "name": "sensorId",
        "in": "query",
        "description": "Device sensor ID filter",
        "required": false,
        "schema": {
          "$ref": "#/components/schemas/sensorId"
        }
      }
    },
    "responses": {
      "400-UserError": {
        "description": "User-side error in request"
      },
      "500-ServerError": {
        "description": "Server-side error in procesing request"
      }
    },
    "schemas": {
      "deviceId": {
        "type": "string",
        "format": "uuid"
      },
      "deviceName": {
        "type": "string"
      },
      "deviceLocation": {
        "type": "string"
      },
      "deviceStatus": {
        "type": "string",
        "enum": [
          "setup",
          "active",
          "lowBattery",
          "inactive",
          "disabled"
        ]
      },
      "sensorId": {
        "type": "string",
        "format": "uuid"
      },
      "alertId": {
        "type": "string",
        "format": "uuid"
      },
      "DeviceGetResp200": {
        "type": "object",
        "properties": {
          "id": {
            "$ref": "#/components/schemas/deviceId"
          },
          "name": {
            "$ref": "#/components/schemas/deviceName"
          },
          "location": {
            "$ref": "#/components/schemas/deviceLocation"
          },
          "status": {
            "$ref": "#/components/schemas/deviceStatus"
          }
        },
        "example": {
          "id": "352b9755-e7de-4a15-bedc-d6af2eb9c755",
          "name": "Example Device",
          "location": "Garden",
          "status": "Active"
        }
      },
      "DevicePostReq": {
        "type": "object",
        "properties": {
          "name": {
            "$ref": "#/components/schemas/deviceName"
          },
          "location": {
            "$ref": "#/components/schemas/deviceLocation"
          }
        },
        "example": {
          "name": "Example Device",
          "location": "Garden"
        }
      },
      "DevicePostResp200": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "record": {
            "type": "object",
            "properties": {
              "id": {
                "$ref": "#/components/schemas/deviceId"
              },
              "name": {
                "$ref": "#/components/schemas/deviceName"
              },
              "location": {
                "$ref": "#/components/schemas/deviceLocation"
              }
            }
          }
        },
        "example": {
          "message": "Device successfully created",
          "record": {
            "id": "352b9755-e7de-4a15-bedc-d6af2eb9c755",
            "name": "Example Device",
            "location": "Garden"
          }
        }
      },
      "DeviceGetSpecificResp200": {
        "type": "object",
        "properties": {
          "id": {
            "$ref": "#/components/schemas/deviceId"
          },
          "name": {
            "$ref": "#/components/schemas/deviceName"
          },
          "location": {
            "$ref": "#/components/schemas/deviceLocation"
          },
          "status": {
            "type": "object",
            "properties": {
              "status": {
                "$ref": "#/components/schemas/deviceStatus"
              },
              "timestamp": {
                "type": "integer"
              }
            }
          },
          "sensors": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/sensorId"
            }
          }
        },
        "example": {
          "id": "352b9755-e7de-4a15-bedc-d6af2eb9c755",
          "name": "Example Device",
          "location": "Garden",
          "status": {
            "status": "active",
            "timestamp": 1647896752
          },
          "sensors": [
            "50eb75f1-a8ab-4057-ac87-016008e2da37",
            "5bd42985-8655-456a-9b9e-bdc0a30c8e48",
            "d7023769-6080-4784-9a53-bb7fa79e54e0"
          ]
        }
      },
      "DevicePutSpecificReq": {
        "type": "object",
        "properties": {
          "name": {
            "$ref": "#/components/schemas/deviceName"
          },
          "location": {
            "$ref": "#/components/schemas/deviceLocation"
          },
          "sensors": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/sensorId"
            }
          }
        },
        "example": {
          "name": "Example Device",
          "location": "Garden",
          "sensors": [
            "50eb75f1-a8ab-4057-ac87-016008e2da37",
            "5bd42985-8655-456a-9b9e-bdc0a30c8e48",
            "d7023769-6080-4784-9a53-bb7fa79e54e0"
          ]
        }
      },
      "DevicePutSpecificResp200": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "record": {
            "type": "object",
            "properties": {
              "id": {
                "$ref": "#/components/schemas/deviceId"
              },
              "name": {
                "$ref": "#/components/schemas/deviceName"
              },
              "location": {
                "$ref": "#/components/schemas/deviceLocation"
              },
              "status": {
                "type": "object",
                "properties": {
                  "status": {
                    "$ref": "#/components/schemas/deviceStatus"
                  },
                  "timestamp": {
                    "type": "integer"
                  }
                }
              },
              "sensors": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/sensorId"
                }
              }
            }
          }
        },
        "example": {
          "message": "Device successfully updated",
          "record": {
            "id": "352b9755-e7de-4a15-bedc-d6af2eb9c755",
            "name": "Example Device",
            "location": "Garden",
            "status": {
              "status": "active",
              "timestamp": 1647896752
            },
            "sensors": [
              "50eb75f1-a8ab-4057-ac87-016008e2da37",
              "5bd42985-8655-456a-9b9e-bdc0a30c8e48",
              "d7023769-6080-4784-9a53-bb7fa79e54e0"
            ]
          }
        }
      },
      "DeviceDeleteSpecificResp200": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "record": {
            "type": "object",
            "properties": {
              "id": {
                "$ref": "#/components/schemas/deviceId"
              },
              "name": {
                "$ref": "#/components/schemas/deviceName"
              },
              "location": {
                "$ref": "#/components/schemas/deviceLocation"
              },
              "status": {
                "type": "object",
                "properties": {
                  "status": {
                    "$ref": "#/components/schemas/deviceStatus"
                  },
                  "timestamp": {
                    "type": "integer"
                  }
                }
              },
              "sensors": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/sensorId"
                }
              }
            }
          }
        },
        "example": {
          "message": "Device successfully deleted",
          "record": {
            "id": "352b9755-e7de-4a15-bedc-d6af2eb9c755",
            "name": "Example Device",
            "location": "Garden",
            "status": {
              "status": "active",
              "timestamp": 1647896752
            },
            "sensors": [
              "50eb75f1-a8ab-4057-ac87-016008e2da37",
              "5bd42985-8655-456a-9b9e-bdc0a30c8e48",
              "d7023769-6080-4784-9a53-bb7fa79e54e0"
            ]
          }
        }
      }
    }
  }
}